baseURL = 'https://dus1098.github.io/'
languageCode = "ko-kr"
title = '몰래하는 블로그'
theme = "PaperMod"

[params]
defaultTheme = "light"          # auto면 환경마다 달라짐
disableThemeToggle = true

[[menu.main]]
name = "여행"
url = "/travel/"
weight = 2

[[menu.main]]
name = "개발"
url = "/dev/"
weight = 1